
version: 2

models:
    - name: stg_top_100_2017
      description: "A starter dbt model"
      columns:
          - name: ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

sources:
  - name: staging
    description: desc
    database: dtc-de-course-375312
    schema: ds_zoomcamp
    tables:
      - name: top100_2017
      - name: top100_2018
      - name: top100_2019
      - name: top100_2020
      - name: top100_2021
      - name: top100_2022